name: Cabinet Smart Contracts Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pact-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Ensure bash is installed
        run: |
          sudo apt-get update && sudo apt-get install -y bash
          echo "Bash version:"
          bash --version

      - name: Install pact
        run: |
          mkdir -p ${{ github.workspace }}/bin
          cd ${{ github.workspace }}/bin

          # Download the latest Pact binary
          wget https://github.com/kadena-io/pact-5/releases/download/5.0/pact-5.0-linux-x64.tar.gz

          # Extract the tar.gz file
          tar -xvzf pact-5.0-linux-x64.tar.gz

          # Ensure the binary is executable
          chmod +x pact

      - name: Run tests.sh script
        run: |
          cd ${{ github.workspace }}/pact
          PACT_BIN=${{ github.workspace }}/bin/pact
          bash tests.sh > tests.log 2>&1
          echo "Output of tests.sh:"
          cat tests.log || echo "tests.log not found!"
